# These github actions will update Terraform section(s) of README(s), and
# perform linting using pre-commit.
---
# yamllint disable rule:line-length
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  # push:
  #   branches-ignore:
  #     - main
permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: dev
    steps:
      - uses: actions/checkout@v4
      - name: Install talisman
        run: |
          sudo curl -sLo /usr/local/bin/talisman https://github.com/thoughtworks/talisman/releases/download/v1.32.0/talisman_linux_amd64
          sudo chmod 0755 /usr/local/bin/talisman
      - name: Install terraform-docs
        run: |
          sudo sh -c 'curl -sL https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz | tar xzf - -C /usr/local/bin'
          sudo chmod 0755 /usr/local/bin/terraform-docs
      - name: Install terragrunt
        run: |
          sudo curl -sLo /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.1/terragrunt_linux_amd64
          sudo chmod 0755 /usr/local/bin/terragrunt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - uses: pre-commit/action@v3.0.1
